### ISSUE TITLE
Tracking Issue for Hardening the Toolings Related to Move on EVM

### ISSUE THREAD

**Issue by vgao1996** [move-language/move#107]
- [ ] Make `--arch ethereum` available in all builds #106
- [ ] Unify `move --ethereum package build` and `move package test --evm`
- [ ] Update the documentation for `move-cli`
- [ ] Remove the `build/evm` directory before starting a new build #105
- [ ] Potential bug: cli tests `rebuild_after_touching_manifest` may fail (due to a preexisting build directory?)
